---
# Role check tasks

- block:
    - name: Gather facts
      setup:
      when: >-
        ansible_facts is not defined
        or ansible_facts.architecture is not defined

    - name: Assert oracle license accepted
      assert:
        that:
          - oracle_java_accept_license | bool

    - block:
        - name: Setup fact with oracle java latest versions
          set_fact:
            oracle_java_latest_versions: >-
              {{ (oracle_java_java_main_site_content
                  | regex_replace("<a", "\n")
                  | regex_replace("</a", "\n")).splitlines()
                 | select("search", "Java SE [0-9\.u]+")
                 | reject("search", "Documentation")
                 | map("regex_replace", ".*Java SE ([0-9\.u]+).*", "\1")
                 | list
                 | unique }}

        - name: Setup fact with oracle java last version
          set_fact:
            oracle_java_latest_version: >-
              {{ oracle_java_latest_versions | first }}

        - name: Setup fact with oracle default artifact
          set_fact:
            oracle_java_default_artifact:
              id: oracle_java
              type: https
              host: "{{ oracle_java_official_download_host }}"
              path: "{{ oracle_java_official_download_path }}"
              file: "{{ oracle_java_official_download_file }}"
              dest: /tmp
              headers:
                cookie: "oraclelicense=accept-securebackup-cookie"
              timeout: 120
              validate_certs: yes
      when: >-
        oracle_java_version == "latest"
        or oracle_java_artifact is undefined

    - name: Assert version to download is valid
      assert:
        that:
          oracle_java_effective_version in oracle_java_latest_versions
      when: oracle_java_artifact is undefined
  tags:
    - role::oracle_java
    - role::oracle_java::check
