---
# Role check tasks

- block:
    - name: Assert oracle license accepted
      assert:
        that:
          - oracle_java_accept_license | bool

    - name: Assert download artifact is valid
      assert:
        that:
          - >-
            oracle_java_artifact is defined
            or oracle_java_effective_version in oracle_java_latest_versions
  tags:
    - role::oracle_java
    - role::oracle_java::check
