---

- name: Check oracle java
  block:
    - name: Gather facts
      ansible.builtin.setup:
      when: >-
        ansible_facts is not defined
        or ansible_facts.architecture is not defined

    - name: Gather oracle java last version
      block:
        - name: Setup fact with oracle java latest versions
          ansible.builtin.set_fact:
            oracle_java_latest_versions: >-
              {{ oracle_java_latest_versions }}

        - name: Setup fact with oracle java last version
          ansible.builtin.set_fact:
            oracle_java_latest_version: >-
              {{ oracle_java_latest_versions | first }}
      when: >-
        oracle_java_version == "latest"
        or oracle_java_artifact is undefined

    - name: Setup fact with oracle java effective version
      ansible.builtin.set_fact:
        oracle_java_effective_version: >-
          {{ (oracle_java_version == "latest")
             | ternary(oracle_java_latest_version | default(""),
                       oracle_java_version) }}

    - name: Setup fact with oracle default artifact
      ansible.builtin.set_fact:
        oracle_java_default_artifact:
          id: oracle_java
          type: https
          host: "{{ oracle_java_official_download_host }}"
          path: "{{ oracle_java_official_download_path }}"
          file: "{{ oracle_java_official_download_file }}"
          dest: /tmp
          timeout: 120
          validate_certs: yes
      when: >-
        oracle_java_version == "latest"
        or oracle_java_artifact is undefined

    - name: Assert version to download is valid
      ansible.builtin.assert:
        that:
          oracle_java_effective_version in oracle_java_latest_versions
      when: oracle_java_artifact is undefined
  tags:
    - role::oracle_java
    - role::oracle_java::check
