---
# Role cleanup tasks

- name: Remove oracle java package
  include_role:
    name: amtega.artifact
  vars:
    override:
      state: absent
    artifact: >-
      {{ oracle_java_artifact
         | default(oracle_java_default_artifact)
         | combine(override) }}
  tags:
    - role::oracle_java
    - role::oracle_java::cleanup
