---
# Role cleanup tasks

- name: Remove oracle java package
  file:
    path: "{{ oracle_java_package }}"
    state: absent
  when:
    - oracle_java_remove_artifact | bool
    - oracle_java_package | length > 0
  tags:
    - role::oracle_java
    - role::oracle_java::cleanup
