---

- name: Configure oracle java
  block:
    - name: Search installed java packages
      ansible.builtin.shell: "rpm -qa | grep jdk | grep {{ pattern }}"
      args:
        warn: no
      register: oracle_java_search_rpm_result
      changed_when: no
      failed_when: no
      vars:
        pattern: >-
          {{ (oracle_java_effective_version is search(".*u.*"))
             | ternary(oracle_java_effective_version
                       | regex_replace("(.*)u(.*)", "1.\1.*_\2"),
                       oracle_java_effective_version) }}

    - name: Search java binaries
      ansible.builtin.shell: >-
        rpm -ql {{ oracle_java_search_rpm_result.stdout }} | grep "/bin/"
      args:
        warn: no
      register: oracle_java_search_binaries_result
      changed_when: no
      when: oracle_java_search_rpm_result.rc == 0

    - name: Setup java home and alternatives
      block:
        - name: Setup fact with the oracle java home
          ansible.builtin.set_fact:
            oracle_java_home: "{{ java_home }}"
          vars:
            java_home: >-
              {{ oracle_java_search_binaries_result.stdout_lines
                 | select("search", "^.*/bin/java$")
                 | list
                 | first
                 | regex_replace("^(.*)/bin/java$", "\1") }}

        - name: Setup alternatives to oracle java
          community.general.alternatives:
            name: "{{ item }}"
            link: "/usr/bin/{{ item | basename }}"
            path: "{{ oracle_java_home }}/bin/{{ item }}"
          loop: "{{ oracle_java_alternatives }}"
          loop_control:
            label: "{{ item | basename }}"
          when:
            - oracle_java_state == "present"
            - oracle_java_update_alternatives | bool
      when: not oracle_java_search_binaries_result is skipped
  tags:
    - role::oracle_java
    - role::oracle_java::configure
