---
# Role install tasks

# We use rpm instead of ansible package module due to several "nothing provides
# ..." error messages when using yum/dnf

- name: Install oracle java package
  command: "rpm -U {{ oracle_java_package }}"
  args:
    warn: no
  when:
    - oracle_java_state == "present"
    - oracle_java_accept_license | bool
    - not oracle_java_check_installed_result.stat.exists
  tags:
    - role::oracle_java
    - role::oracle_java::install
