---

- name: Setup oracle java
  block:
    - ansible.builtin.import_tasks: check.yml
    - ansible.builtin.import_tasks: download.yml
    - ansible.builtin.import_tasks: install.yml
    - ansible.builtin.import_tasks: configure.yml
    - ansible.builtin.import_tasks: uninstall.yml
    - ansible.builtin.import_tasks: cleanup.yml
  tags:
    - role::oracle_java
