---
# Role uninstall tasks

- block:
    # rpm is used here instead of `package` module because seems that in fedora
    # 27/28 this module does not remove the package and returns `Nothing to do`

    - name: Uninstall oracle java package
      command: "rpm -e {{ oracle_java_search_rpm_result.stdout }}"
      args:
        warn: false
      register: oracle_java_uninstall_package_result
      changed_when: oracle_java_uninstall_package_result.rc == 0
      failed_when: oracle_java_uninstall_package_result.rc == 1
      when: oracle_java_search_rpm_result.rc == 0

    - name: Remove alternatives to oracle java binaries
      command: >-
        update-alternatives
        --remove {{ item | basename }}
        {{ item }}
      register: oracle_java_remove_alternatives_result
      changed_when: oracle_java_remove_alternatives_result.rc == 0
      failed_when: false
      when:
        - oracle_java_update_alternatives
        - not oracle_java_search_binaries_result is skipped
      loop: "{{ oracle_java_alternatives }}"
      loop_control:
        label: "{{ item }}"
  when: oracle_java_state == "absent"
  tags:
    - role::oracle_java
    - role::oracle_java::uninstall
