---

dependency:
  name: galaxy
  enabled: yes
  options:
    ignore-certs: yes
    ignore-errors: yes
    role-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
    requirements-file: >-
      ${MOLECULE_SCENARIO_DIRECTORY}/../resources/requirements.yml
driver:
  name: docker
lint: "${MOLECULE_SCENARIO_DIRECTORY}/../resources/linters.sh"
platforms:
  - name: "centos7-${INSTANCE_UUID:-1}"
    image: centos:7
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_7
  - name: "centos8-${INSTANCE_UUID:-1}"
    image: centos:8
    groups:
      - molecule_hosts
      - molecule_hosts_centos
      - molecule_hosts_centos_8
  - name: "fedora33-${INSTANCE_UUID:-1}"
    image: fedora:33
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_33
  - name: "fedora34-${INSTANCE_UUID:-1}"
    image: fedora:34
    groups:
      - molecule_hosts
      - molecule_hosts_fedora
      - molecule_hosts_fedora_34
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_enabled: profile_tasks
      action_plugins: $PWD/action_plugins
  playbooks:
    cleanup: ../resources/cleanup.yml
    prepare: ../resources/prepare.yml
    converge: ../resources/converge.yml
    side_effect: ../resources/side_effect.yml
  inventory:
    hosts:
      molecule_hosts:
        vars:
          oracle_java_state: absent
          oracle_java_version: latest
          oracle_java_accept_license: yes
      molecule_hosts_fedora:
        vars:
          ansible_python_interpreter: /usr/bin/python3
verifier:
  name: ansible
