---

- name: Verify
  hosts: molecule_hosts
  gather_facts: no
  tasks:
    - name: Check java is not installed
      ansible.builtin.command: /usr/bin/java -version
      changed_when: no
      register: check_java_result
      failed_when: >-
        check_java_result.rc == 0
        and check_java_result.stderr is search("Java.* SE Runtime Environment")
